### ISSUE TITLE
Доработать функцию _convertRows

### ISSUE THREAD

**Issue by YadrovSergey** [YadrovSergey/websqljs#6]
Для каждой строки вызвается tryJSON - может влиять на производительность. Если я решу хранить объект json ввиде строки, то он преобразется в объект.
Для каждого числа вызывается tryDate -  а если это будет действительно большле число.

Поэтому нужно конвертировать в соответсвии с структурой переданной функцией createTable
Например:
1. Вызывается функция createTable (она всегда вызывается перед выполнением других функций) - добавляем в объект-кэш - тип переменной.
cache[ИмяТаблицы+"=="+ИмяСтолбца] = тип переменной
2. В функцию convertRows передать имя таблицы и проверять необходимость конвертации по объекту-кэшу cache

**Comment by desker** [comment]
Done
