### ISSUE TITLE
Функция find

### ISSUE THREAD

**Issue by YadrovSergey** [YadrovSergey/websqljs#7]
Добавить в cond (но не обязательно их наличие):
1. limit - ограничение по выборке. Не задано, то не устанавливается
2. select - строка с полями для выборки. Т.е. если указан select, то вместо \* будет строка select 

Добавить параметр row (по умолчанию false)
Если true, то не будет вызваться функция var result = self._convertRows(res); и в колбэк вернется sql выборка.

**Comment by desker** [comment]
Fixed
